blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from django.contrib import admin
from .views import (
    BlogHomePageView,
    # PostDetailView,
)

from . import views

app_name='blog'

urlpatterns = [
    path('',BlogHomePageView.as_view(),name='home'),
    path('<int:pk>/',views.PostDetailView.as_view(),name='post-detail'),
    path('create/',views.image_upload_view,name='create-post'),

    path('<int:pk>/like/',views.AddLike.as_view(),name='like'),
    path('<int:pk>/dislike/',views.AddDislike.as_view(),name='dislike'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import (
    HomePageView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('',HomePageView.as_view(),name='Home'),
    path('blog/', include('blog.urls',namespace='blog')),
    path('accounts/', include('users.urls',namespace='users')),
]

users/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name='account'

urlpatterns = [
    path('register/',views.register,name="register"),
    path('edit-profile/',views.editProfile,name="edit-profile"),
    path('profile/',views.profile,name="profile"),
    path('login/',auth_views.LoginView.as_view(),name="login"),
    path('logout/',auth_views.LogoutView.as_view(),name="logout"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    class PostObjects(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')
    options =(
        ('draft','Draft'),
        ('published','Published')
    )

    title = models.CharField(max_length=255)
    category = models.ForeignKey(Category,on_delete=models.SET('Categoria eliminada'),default=1)
    content = models.TextField()
    image = models.ImageField(null=True,upload_to='image-post')
    likes = models.ManyToManyField(User,related_name='post_like')
    dislikes = models.ManyToManyField(User,related_name='post_dislike')
    published = models.DateTimeField(default=timezone.now,editable=False)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    status = models.CharField(max_length=20,choices=options,default='published')
    objects = models.Manager()
    Postobjects = PostObjects()

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('published',)

def get_sentinel_user():
    return User().objects.get_or_create(username='deleted')[0]


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name="comments")
    name = models.ForeignKey(User,on_delete=models.SET(get_sentinel_user))
    content = models.TextField()
    publish_date = models.DateTimeField(default=timezone.now)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ("publish_date",)

        def __str__(self):
            return f"comment by: {self.name}"

blog/forms.py
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post,Comment

class PostCreateView(forms.ModelForm,LoginRequiredMixin):
    # title = forms.CharField(label='nigga',widget=forms.CharField(attrs={'class':'a'}))
    title = forms.CharField(label='nigga',
        widget=forms.TextInput(attrs={
            'placeholder':'Title',
            # 'class':'border-2 border-rose-500'
            }
            )
        )
    

    class Meta:
        model = Post
        fields = ('title','category','content','image','status')

    def form_valid(self,form):
        if form.is_valid():
            form.instance.author = self.request.user
            return super().form_valid(form)

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(attrs={
        'class':'comment-post-input',
        'rows':3,
        'paceholder':'Comment something',})
    )
    class Meta:
        model = Comment
        fields = ('content',)
    def form_valid(self,form):
        if form.is_valid():
            form.instance.name = self.request.user
            return super().form_valid(form)

blog/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post,Comment
from .forms import PostCreateView,CommentForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse

class BlogHomePageView(TemplateView):
    template_name='blog/index.html'    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.Postobjects.all()
        return context


class PostDetailView(LoginRequiredMixin,View):
    def get(self,request,pk,*args,**kwargs):
        
        post = Post.objects.get(pk=pk)
        form = CommentForm()

        comments=Comment.objects.filter(post=post).order_by('publish_date')

        context = {
            'post':post,
            'form':form,
            'comments':comments
        }
        return render(request,'blog/post-detail.html',context)
        
    def post(self,request,pk,*args,**kwargs):
        if request.method == 'POST':
            post = Post.objects.get(pk=pk)
            form = CommentForm(request.POST)
            comments=Comment.objects.filter(post=post).order_by('publish_date')

            if form.is_valid():
                comment = form.save(commit=False)
                comment.name = request.user
                comment.post = post
                comment.save()
                # comment.save()
                return redirect('blog:post-detail',pk)

            context = {
                'post':post,
                'form':form,
                'comments':comments
            }
        return render(request,'blog/post-detail.html',context)

    
@login_required
def image_upload_view(request):
    if request.method == 'POST':
        form = PostCreateView(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            img_obj = form.instance
            return render(request, 'index.html', {'form': form, 'img_obj': img_obj})
    else:
        form = PostCreateView()
    return render(request, 'blog/upload-post.html', {'form': form})



  


class AddLike(LoginRequiredMixin,View):
    def post(self,request,pk,*args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_dislike = False
        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break
        
            if dislike:
                post.dislikes.remove(request.user)


        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.likes.add(request.user)
            post.dislikes.remove(request.user)

        if is_like:
            post.likes.remove(request.user)

        
        return redirect('blog:post-detail',pk)

class AddDislike(LoginRequiredMixin,View):
    def post(self,request,pk,*args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_like = False
        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break
        
        if is_like:
            post.likes.remove(request.user)

        is_dislike = False
        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add(request.user)
            post.likes.remove(request.user)
        
        if is_dislike:
            post.dislikes.remove(request.user)
        
        return redirect('blog:post-detail',pk)

templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static '../static/css/blog.css' %}">
{% block title %}Ninerogues - HomePage{% endblock %}
{% block  content %}
    <h1 class="title">Blog Home Page</h1>
    <br>
    <div class="cuadrado"></div>
    <section class="post">
        <div>
            <div class="post-container">
                {% for post in posts %}
                    <article class="post-columna">
                    <a href="{% url 'blog:post-detail' pk=post.pk %}">    
                        <img src="../blog{{post.image.url}}"alt="Post">
                    </a>
                    <a href="{% url 'blog:post-detail' pk=post.pk %}">
                        <h3>{{post.title}}</h3>
                    </a><br>
                    <a href="{% url 'blog:post-detail' pk=post.pk %}">
                        {{post.content}}
                    </a>
                    </article>
                    {% endfor %}
            </div>
            </div>
    </section> 
    </div>
{% endblock content %}

templates/blog/post-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    </br></br></br></br></br>
    <div class="cuadrado"></div>
        <section class="productos">
            <div>
                <div class="contenedor">
                    <article class="productos_columna">
                        <div>
                            <h3>{{post.title}}</h3></br>
                            <img src="../../blog{{post.image.url}}"alt="{{post.title}}">
                            <h3>{{post.content}}</h3></br>
                            <h3>{{post.published}}</h3></br>
                            <h3>Posted by: {{post.author}}</h3>
                            <br> 
                            {% if user.is_authenticated %}
                            <form method="POST" enctype="multipart/form-data" class="form-comment">
                                {% csrf_token %}
                                <div class="img-user-comment-container">
                                    <img class="img-user-comment" src="{% url 'account:profile' %}..{{user.profile.image.url}}" alt="{{user.username}}">
                                </div>
                                <div class="comment-post-container">
                                    {{form.content}}
                                </div><br><br>
                                <button type="submit" class="comment-button">Comment</button>
                              </form>
                            {% endif %}
                            <br><br>
                            {% for comment in comments %}
                                <h3>{{comment.content}}</h3><br>
                                <h3>{{comment.name}}</h3><br>
                            {% endfor %}
                        </div>
                        <form method="POST" action="{% url 'blog:like' post.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="comment-button">Like</button>
                            {% comment %} <i type="submit" class="bi bi-hand-thumbs-up"></i> {% endcomment %}
                        </form>
                        <h3>{{post.likes.all.count}}</h3><br>
                        <form method="POST" action="{% url 'blog:dislike' post.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="comment-button">Dislike</button>
                        </form>
                        <h3>{{post.dislikes.all.count}}</h3><br>
                    </article>
                </div>
            </div>
        </section>
    </div>
    </br>
    
{% endblock content %}

templates/blog/upload-post.html
{% extends 'base.html' %}
{% comment %} {% load widget_tweaks %} {% endcomment %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <br><br><br><br>
    <div class="container mx-auto">
        <form method="POST" enctype="multipart/form-data" class="ml-2">
            {% csrf_token %}
            <div>
                <h2>Create a post<h2>
            </div>
            <br>
            <div >{{form.title}}</div><br>
            <div>
                <h4>Category<h4>
                {{form.category}}
            </div><br>
            <div>{{form.content}}</div><br>
            <div>{{form.image}}</div><br>
            <div>
                <h4>Status<h4>
                {{form.status}}
            </div><br>
            <div class="border-2 border-blue-500">
                <button type="submit" >Upload Post</button>
            </div>
            <br><br><br>
        </form>
    </div>
</body>
</html>
{% endblock content %}