blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from django.contrib import admin
from .views import (
    BlogHomePageView,
    # PostDetailView,
)

from . import views

app_name='blog'

urlpatterns = [
    path('',BlogHomePageView.as_view(),name='home'),
    path('<int:pk>/',views.PostDetailView.as_view(),name='post-detail'),
    path('create/',views.image_upload_view,name='create-post'),

    path('<int:pk>/like/',views.AddLike.as_view(),name='like'),
    path('<int:pk>/dislike/',views.AddDislike.as_view(),name='dislike'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import (
    HomePageView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('',HomePageView.as_view(),name='Home'),
    path('blog/', include('blog.urls',namespace='blog')),
    path('accounts/', include('users.urls',namespace='users')),
]

users/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name='account'

urlpatterns = [
    path('register/',views.register,name="register"),
    path('edit-profile/',views.editProfile,name="edit-profile"),
    path('profile/',views.profile,name="profile"),
    path('login/',auth_views.LoginView.as_view(),name="login"),
    path('logout/',auth_views.LogoutView.as_view(),name="logout"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(null=True,blank=True,default='media/profile-img/default.png',upload_to='profile-img')
    if image.null == True:
        image.default='profile-img/default.png'

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','username','email','password1','password2']
    
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

backend/users/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import is_valid_path
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

def register(request):
    if request.method == 'POST':
        form =  UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'account created for {username}')
            return redirect('../../blog/')
    else:
        form = UserRegisterForm()
    return render(request,'users/register.html',{'form': form})

@login_required

def editProfile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f'Your account has been updated!')
            return redirect('../profile')
        elif u_form.is_valid() == False or u_form.is_valid() == False:
            return redirect('../edit-profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        if u_form.is_valid() == None and p_form.is_valid() == None:
            return redirect('../edit-profile')

    context = {
        'u_form':u_form,
        'p_form':p_form
    }

    return render(request,'users/edit-profile.html',context)

def profile(request):
    return render(request,'users/profile.html')

users/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.views.generic import TemplateView
from blog.models import Post
from .models import User


def register(request):
    if request.method == 'POST':
        form =  UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'account created for {username}')
            return redirect('../../blog/')
    else:
        form = UserRegisterForm()
    return render(request,'users/register.html',{'form': form})

@login_required

def editProfile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f'Your account has been updated!')
            return redirect('../profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        if u_form.is_valid() == None and p_form.is_valid() == None:
            return redirect('../profile')

    context = {
        'u_form':u_form,
        'p_form':p_form
    }

    return render(request,'users/edit-profile.html',context)

@login_required
def profile(request):
  user = request.user
  profile = User.objects.filter(username = user)
  posts = Post.objects.filter(author_id= user)

  return render(request,"users/profile.html",{
    "user" : user,
    "profile" : profile,
    "posts" : posts,
  })

templates/users/edit-profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        {{user.username}}
    </h1>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{u_form.as_p}}
            {{p_form.as_p}}
            <br>
            <button type="submit">Upload</button>
        </form>
    </div>
</body>
</html>

<style>
    input[type="checkbox"] {
        display:none;
    }
    input[type="checkbox"] + label{
        display:none;
    }
</style>
{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="login-container">
        <div class="img-container">
            <img src="../media/assets/user-login.png">
        </div>
        <form method="POST" enctype="multipart/form-data" class="login-form">
            {% csrf_token %}
            <div>
                <h4>Username<h4>
                {{form.username}}
            </div>
            <div>
                <h4>password<h4>
                {{form.password}}
            </div>
            <button type="submit" class="login-button">Login</button>
            <br>
            <small>
                Not have an account? <a href="{% url 'account:register' %}">create account</a>
            </small>
        </form>
    </div>
</body>
</html>
{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static '../../static/css/profile.css' %}">
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Profile{% endblock %}</title>
</head>
<body>
<header>
	<div class="container">
		<div class="profile">
			<div class="profile-image">
				<img src="{% url 'account:profile' %}..{{user.profile.image.url}}" alt="{{user.username}}">
			</div>
			<div class="profile-user-settings">
				<h1 class="profile-user-name">{{user.username}}</h1>
				<a href="{% url 'account:edit-profile' %}"><button class="btn profile-edit-btn">Edit Profile</button></a>
				<button class="btn profile-settings-btn" aria-label="profile settings"><i class="fas fa-cog" aria-hidden="true"></i></button>
			</div>
            <div class="profile-bio">
				<p><span class="profile-real-name">{{user.first_name}}</p>
			</div> 
			<div class="profile-stats">
				<ul>
                    <li><span class="profile-stat-count">{{posts.count}}</span> posts</li>
					<li><span class="profile-stat-count">188</span> followers</li>
					<li><span class="profile-stat-count">206</span> following</li>
				</ul>
			</div>
			
		</div>
		<!-- End of profile section -->
	</div>
</header>
<h1>Publicaciones</h1><br>
<main>
    <section class="profile-post">
        <div>
            <div class="profile-post-container">
            {% for post in posts %}
                <article class="profile-post-columna">
                <a href="{% url 'blog:post-detail' pk=post.pk %}">    
                    <img src="../../blog{{post.image.url}}"alt="Post">
                </a>
                <a href="{% url 'blog:post-detail' pk=post.pk %}">
                    <h3>{{post.title}}</h3>
                </a><br>
                <a href="{% url 'blog:post-detail' pk=post.pk %}">
                    <h3>Posted by: {{post.author}}</h3>
                </a><br>
                <a href="{% url 'blog:post-detail' pk=post.pk %}">
                    <h3>{{post.published}}</h3>
                </a>
                </article>
                {% endfor %}
            </div>
        </div>
    </section> 
    </div> 
</main>
</body>
</html>
{% endblock content %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="login-container">
        <div class="img-container">
            <img src="../media/assets/user-login.png">
        </div>
        <form method="POST" enctype="multipart/form-data" class="login-form">
            {% csrf_token %}
            <div>
                <h4>Name<h4>
                {{form.first_name}}
            </div>
            <div>
                <h4>Username<h4>
                {{form.username}}
            </div>
            <div>
                <h4>Email<h4>
                {{form.first_name}}
            </div>
            <div>
                <h4>Password<h4>
                {{form.password1}}
            </div>
            <div>
                <h4>Repeat password<h4>
                {{form.password2}}
            </div>
            <button type="submit" class="login-button">Login</button>
            <br>
            <small>
                Already have an account? <a href="{% url 'account:login' %}">Sign in</a>
            </small>
        </form>
    </div>
</body>
</html>
{% endblock content %}